### ISSUE TITLE
add coveralls to travis

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-quality-filter#26]

**Comment by jairideout** [comment]
@gregcaporaso when you do this, can you match the style of .travis.yml files we have in other org repos? We'd like to keep these .travis.yml files as consistent as possible b/c in the future we may have a tool that auto-generates them (having consistent files will make developing that tool easier). See [q2-feature-table's .travis.yml](https://github.com/qiime2/q2-feature-table/blob/master/.travis.yml) for an example.
