### ISSUE TITLE
would a `filter-fasta` method be appropriate in this plugin?

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-quality-filter#29]
**Improvement Description**
It would be useful to replicate the functionality of qiime1's [`filter_fasta.py`](http://qiime.org/scripts/filter_fasta.html) — e.g., [see this forum post](https://forum.qiime2.org/t/use-qiime2-in-agp/677/3).

**Comments**
I am not sure whether this would be at home in `q2-quality-filter`, `demux`, or some other plugin that has yet to be created (`q2-filter-everything-under-the-sun`).

Whichever plugin would be appropriate (and perhaps this is an argument for making a new plugin, or for combining with the two demultiplexing plugins into a single fastq/fasta handling plugin), I could imagine other fasta/fastq functions that could accompany this, e.g., trimming, subsampling.

**References**
[`filter_fasta.py`](http://qiime.org/scripts/filter_fasta.html) — e.g., [see this forum post](https://forum.qiime2.org/t/use-qiime2-in-agp/677/3)

**Comment by thermokarst** [comment]
This functionality was implemented for `FeatureData[Sequence]` in QIIME 2 2017.9: https://forum.qiime2.org/t/qiime-2-2017-9-release-is-now-live/1160
