### ISSUE TITLE
quality filtering of paired end reads

### ISSUE THREAD

**Issue by Attayeb** [qiime2/q2-quality-filter#51]
I ran 
```qiime quality-filter q-score --i-demux artifacts/samples.qza --output-dir quality-filtered.qza```

samples.qza has two paired end samples
* S1_R1.fastq
* S1_R2.fastq
* S2_R1.fastq
* S2_R2.fastq

the quality-filtered.qza file has 2 files only
S1_R1.fastq
S2_R1.fastq

I expected four files. 

How can I solve this problem

**Comment by thermokarst** [comment]
Please post user support questions to the [QIIME 2 Forum](https://forum.qiime2.org). Thanks!
